In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("raw_data.csv")
df2 = df.copy()
df2["tax"] = df2["income"].apply(lambda x: "20%" if x > 50000 else "10%")
gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)
df2.assign(new_income = df2["income"] * 1.1)
df2["country"] = df2["country"].replace("USA", "US")

df2.rename(columns = {"income": "Salary", "tax": "Tax"})
df2.rename(index={1: "1st"})
df2.sort_values(["income", "age"])

    id          name   age country gender   income  tax
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
3    3          Alex   NaN      US      U  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%

In [18]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN      US      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%