In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [85, 40, 95, 30],
    'Passed': ['Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)
df

      Name  Score Passed
0    Alice     85    Yes
1      Bob     40     No
2  Charlie     95    Yes
3    David     30     No

In [2]:
winners = df[df["Passed"] == "Yes"]
winners

      Name  Score Passed
0    Alice     85    Yes
2  Charlie     95    Yes

In [3]:
df

      Name  Score Passed
0    Alice     85    Yes
1      Bob     40     No
2  Charlie     95    Yes
3    David     30     No

In [4]:
only_bob = df[df["Name"] == "Bob"]
high_scores = df[df["Score"] > 50]
avg_score = high_scores["Score"].mean()
name_sort = df.sort_values("Name", ascending=True)
only_score = df[["Score"]]
max_score = only_score.max()
max_score

Score    95
dtype: int64

In [5]:
# Adding a row with a missing value
import numpy as np
df.loc[4] = ["Eve", np.nan, "No"]

In [6]:
df_clean = df.dropna()
df_clean

      Name  Score Passed
0    Alice   85.0    Yes
1      Bob   40.0     No
2  Charlie   95.0    Yes
3    David   30.0     No

In [10]:
df.loc[4] = ["Azra", np.nan, "No"]
avg_score = df["Score"].mean()
avg_score

np.float64(62.5)

In [11]:
df

      Name  Score Passed
0    Alice   85.0    Yes
1      Bob   40.0     No
2  Charlie   95.0    Yes
3    David   30.0     No
4     Azra    NaN     No

In [14]:
df["Score"] = df["Score"].fillna(avg_score)

      Name  Score Passed
0    Alice   85.0    Yes
1      Bob   40.0     No
2  Charlie   95.0    Yes
3    David   30.0     No
4     Azra   62.5     No