In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tested.csv")

In [3]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [4]:
avg_age = df["Age"].median()
df["Age"] = df["Age"].fillna(avg_age)

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [6]:
df = df.drop("Cabin", axis=1)

In [7]:
avg_fare = df["Fare"].mean()
avg_fare

np.float64(35.627188489208635)

In [8]:
df["Fare"] = df["Fare"].fillna(avg_fare)
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [15]:
df = df.drop(["Name", "Ticket", "Embarked"], axis=1)
df

KeyError: "['Name', 'Ticket'] not found in axis"

In [10]:
gender_map = {"male": 0, "female": 1}
df["Sex"] = df["Sex"].map(gender_map)

In [13]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [16]:
df = df.drop(["Embarked"], axis=1)
df

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch      Fare
0            892         0       3    0  34.5      0      0    7.8292
1            893         1       3    1  47.0      1      0    7.0000
2            894         0       2    0  62.0      0      0    9.6875
3            895         0       3    0  27.0      0      0    8.6625
4            896         1       3    1  22.0      1      1   12.2875
..           ...       ...     ...  ...   ...    ...    ...       ...
413         1305         0       3    0  27.0      0      0    8.0500
414         1306         1       1    1  39.0      0      0  108.9000
415         1307         0       3    0  38.5      0      0    7.2500
416         1308         0       3    0  27.0      0      0    8.0500
417         1309         0       3    0  27.0      1      1   22.3583

[418 rows x 8 columns]

In [18]:
from sklearn.model_selection import train_test_split

X = df.drop("Survived", axis=1)
Y = df["Survived"]

In [23]:
Y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.20, random_state=42)

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
# Create the model
model = RandomForestClassifier()

# 'Fit' is the AI term for 'Learning'
model.fit(X_train, y_train)

# Check the accuracy score
score = model.score(X_test, y_test)
print(f"Accuracy: {score * 100}%")

Accuracy: 100.0%

In [28]:
df

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch      Fare
0            892         0       3    0  34.5      0      0    7.8292
1            893         1       3    1  47.0      1      0    7.0000
2            894         0       2    0  62.0      0      0    9.6875
3            895         0       3    0  27.0      0      0    8.6625
4            896         1       3    1  22.0      1      1   12.2875
..           ...       ...     ...  ...   ...    ...    ...       ...
413         1305         0       3    0  27.0      0      0    8.0500
414         1306         1       1    1  39.0      0      0  108.9000
415         1307         0       3    0  38.5      0      0    7.2500
416         1308         0       3    0  27.0      0      0    8.0500
417         1309         0       3    0  27.0      1      1   22.3583

[418 rows x 8 columns]